name: PR Checks

on:
  pull_request:
permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        version: [latest, latest, latest]
        os: [ubuntu, windows]

    runs-on: ${{ matrix.os }}-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run fmt
        run: cargo fmt -- --check
      - name: Run clippy
        run: cargo clippy -- -Dwarnings